# Offer Statuses
OFFER_STATUS_ACCEPTED = 'Accepted'
OFFER_STATUS_PENDING = 'Pending'
OFFER_STATUS_REJECTED = 'Rejected'
OFFER_STATUSES = [OFFER_STATUS_ACCEPTED, OFFER_STATUS_PENDING, OFFER_STATUS_REJECTED]

# Races
RACE_DWARF = 'Dwarf'
RACE_ELF = 'Elf'
RACE_WIZARD = 'Wizard'
RACES = [RACE_DWARF, RACE_ELF, RACE_WIZARD]

# Weapon Variants
WEAPON_AXE = 'Axe'
WEAPON_STAFF = 'Staff'
WEAPON_SWORD = 'Sword'
WEAPON_CATEGORIES = [WEAPON_AXE, WEAPON_STAFF, WEAPON_SWORD]
